# Generated by Django 4.2 on 2023-07-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/', verbose_name='CSV File')),
                ('file_description', models.TextField(verbose_name='CSV File Description')),
            ],
        ),
    ]
