# Generated by Django 4.2 on 2024-07-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_file_uploaded_at_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(blank=True, default='<function', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='csv_files/', verbose_name='CSV File'),
        ),
    ]
