# Generated by Django 4.2 on 2024-07-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_file_slug_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
